### ISSUE TITLE
Website hosting

### ISSUE THREAD

**Issue by dotemacs** [reclojure/reclojure.org#2]
How do we test that the particular page/path will work?

Should I just create a page `/foo.html` or a directory `/foo/` and create a PR or ...? 

Thanks

**Comment by reborg** [comment]
Depending on your need. For development, I just load the index.html file in a browser. For testing, you can use `cd reclojure.org` and `python -m SimpleHTTPServer`. However, if you need to setup redirect and stuff, you can do that locally with some webserver, but the final test will need to happen on the actual server, which on @dharrigan has access to. But if everything sort of work on your local setup, I doubt we need more QA than this.

**Comment by dotemacs** [comment]
Hey @reborg I think all of us know how it can work on the local machine.

My question was specifically for @dharrigan because he knows the environment where this is hosted.

**Comment by dharrigan** [comment]
Hi,

The content is server via an instance of NGINX.

Previously, I would just load the content into my browser via the file
system. If it looked okay, I would rsync it up.

-=david=-

I prefer encrypted and signed messages.
GPG Fingerprint: 110AF423364754E2880FADAD1C5285BFB20A22F9

No trees were harmed in the sending of this message, however, a number
of electrons were inconvenienced.

This email is sent without prejudice.

**Comment by reborg** [comment]
> Hey @reborg I think all of us know how it can work on the local machine.

The question was generic, (no local or remote specified). I answered generically. And I'm trying to help most of all, not trying to assume what you could already know or not.

> 
> My question was specifically for @dharrigan because he knows the environment where this is hosted.

Better address David (as you did) if the question was specifically for him.

**Comment by dotemacs** [comment]
> > Hey @reborg I think all of us know how it can work on the local machine.
> 
> The question was generic, (no local or remote specified). I answered generically. And I'm trying to help most of all, not trying to assume what you could already know or not.

OK.
 
> > My question was specifically for @dharrigan because he knows the environment where this is hosted.
> 
> Better address David (as you did) if the question was specifically for him.

OK. I just assumed that David would be on it first, because he chose the admin setup and he has admin access.

In future, I'll specifically mention him.

Thanks
